version: "3.7"

services:
    database:
        platform: linux/x86_64
        image: mysql
        container_name: "mysql-db"
        restart: "always"
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: Yahoo123
            MYSQL_DATABASE: bowlera
            MYSQL_USER: bowluser
            MYSQL_PASSWORD: Yahoo123
        volumes:
            - ./database/init:/docker-entrypoint-initdb.d
            - ./database/data:/var/lib/mysql
        networks:
            - bowleranet
    nginx:
        build: ./nginx
        container_name: "nginx"
        restart: "always"
        ports:
            - "80:80"
        networks:
            - bowleranet
    uwsgi-flask:
        build: ./uwsgi-flask
        container_name: "uwsgiflask"
        restart: "always"
        environment:
            - APP_NAME=BowleraApp
        expose:
            - "8081"
        networks:
            - bowleranet
    db-client:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
        networks: 
            - bowleranet

networks:
    bowleranet:
        name: bowleranet
        
